apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gs
    spec:
      containers:
      - name: ping
        image: quay.io/mhausenblas/grpc-gs:0.2
        ports:
        - containerPort: 50051
          protocol: TCP
