apiVersion: v1
kind: Service
metadata:
  name: gs
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: map-gs
      grpc: true
      prefix: /helloworld.Greeter/
      rewrite: /helloworld.Greeter/
      service: gs:9001
spec:
  type: NodePort
  ports:
  - nodeport: 31000
    port: 9001
    targetPort: 50051
  selector:
    app: gs
