---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ambassador
  name: ping-proxy
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: map-ping
      grpc: true
      prefix: /yages.Echo/
      rewrite: /yages.Echo/
      service: ping:9000
spec:
  type: NodePort
  ports:
  - nodePort: 30001
    port: 9000
    targetPort: 9000
  selector:
    app: ping
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ambassador
  name: gs-proxy
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: map-gs
      grpc: true
      prefix: /helloworld.Greeter/
      rewrite: /helloworld.Greeter/
      service: gs:9001
spec:
  type: NodePort
  ports:
  - nodePort: 30002
    port: 9001
    targetPort: 9001
  selector:
    app: gs