---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ambassador
  name: gs-proxy
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: map-gs
      grpc: true
      prefix: /helloworld.Greeter/
      rewrite: /helloworld.Greeter/
      service: gs-proxy:9001
      # ---
      # apiVersion: ambassador/v0
      # kind: Mapping
      # name: map-ping
      # grpc: true
      # prefix: /yages.Echo/
      # rewrite: /yages.Echo/
      # service: ping:9000
spec:
  type: NodePort
  ports:
  - nodePort: 32123
    port: 9001
    targetPort: 50051
  selector:
    app: gs