apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: yages
  name: ping
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
      - name: ping
        image: quay.io/mhausenblas/yages:0.1.0
        ports:
        - containerPort: 9000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: yages
  name: ping
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: ping